spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.188.128:3306/gulimall_ums
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-member

mybatis-plus:
  mapper-locations: classpath:/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000