spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.188.128:3306/gulimall_wms
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
